### ISSUE TITLE
Gmail Notifier Plus is a Windows app that's been around since 2009

### ISSUE THREAD

**Issue by shellscape** [alexis-jaksone/fastest-gmail#8]
Nice extension! Unfortunately it uses the exact name of an app that's been around since 2009. 

https://github.com/shellscape/Gmail-Notifier-Plus
http://shellscape.org/#gnp
http://www.neowin.net/forum/topic/777838-rel-gmail-notifier-plus-for-windows-7/

**Comment by alexis-jaksone** [comment]
Hey @shellscape, please note I am publishing the extension as Gmail**™** Notifier Plus. BTW, I am not sure why you want me to change the name as you don't have any Firefox extension with the same name. Is it okay with you if a note is added to the description stating this extension has noting to do with your Windows app?

**Comment by shellscape** [comment]
@alexis-jaksone an attribution would be nice, but it's still the same exact name. adding a ™ doesn't change that, as that's a meta character. your extension performs the same functions as my app, so the fact that it's executed within firefox versus a native app is really moot.

it's generally considered polite and good form in open source to rebrand when you choose to name a project exactly the same as another project with long-standing prior art and publication. especially when it's the same name as an application which does the same thing.

**Comment by alexis-jaksone** [comment]
Okay then, since having a note in the description is not satisfying you, I changed the name to "Gmail™ Notifier +"
